Skip to content
Product
Solutions
Open Source
Pricing
Search
Sign in
Sign up
level09
/
enferno
Public
Code
Issues
4
Pull requests
Actions
Projects
Wiki
Security
Insights
enferno/docker-compose.yml
@MMSs
MMSs fix for attaching current development folder as a volume to website c…
…
Latest commit fcf4a8c on Feb 20, 2019
 History
 2 contributors
@level09@MMSs
60 lines (52 sloc)  954 Bytes

version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:9.5'

    enviroment:
	- POSTGRES_USER=postgres
	- POSTGRES_PASWORD=postgres
    env_file:
      - '.env'
    volumes:
      - './postgres-data:/var/lib/postgresql'
    ports:
      - '5432:5432'


  website:
    container_name: website
    build: .
      

    volumes:
      - '.:/app'
    ports:
      - '8000:5000'


volumes:
  enferno:
  redis:
  db:
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
enferno/docker-compose.yml at master · level09/enferno · GitHub